spring:
  application:
    name: auth

  profiles:
    active: local

  messages:
    basename: i18n/messages
    cache-duration: -1
    encoding: UTF-8

  config:
    import: optional:classpath:.env.properties

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

exe:
  security:
    jwt:
      expiration: ${SPRING_JWT_EXPIRATION}
      refresh-token:
        expiration: ${SPRING_JWT_REFRESH_TOKEN_EXPIRATION}
      secret-key: ${SPRING_JWT_SECRET}
