name: plango

services:
  redis:
    image: redis:8.2.1-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - plango-infra

  postgres:
    image: postgres:16.10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plango
    restart: unless-stopped
    networks:
      - plango-infra

networks:
  plango-infra:
    driver: bridge
